/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import beans.Administrador;
import beans.Sede;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.LinkedList;
import javax.swing.JPanel;
import log.SedeLog;

/**
 *
 * @author alfie
 */
public class DashboardAdmin extends javax.swing.JFrame {
    private static final int bg = -11515579;
    public static Administrador admin; //datos del usuario de la cuenta
    public static Sede sede; //carga la sede del usuario de la cuenta
    public static LinkedList<Sede> listSede = new SedeLog().lista(); // carga todas las sedes
    
    /**
     * Creates new form PrincipalAdmin
     */
    public DashboardAdmin() {
        initComponents();
        setColor(btnInicio);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panHeader = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        panLateral = new javax.swing.JPanel();
        panBotones = new javax.swing.JPanel();
        btnInicio = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        btnPlanCurricular = new javax.swing.JPanel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        btnEvaluacion = new javax.swing.JPanel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        btnResEstudiante = new javax.swing.JPanel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        btnCursos = new javax.swing.JPanel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        btnEstudiantes = new javax.swing.JPanel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JPanel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        btnAsignar = new javax.swing.JPanel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        btnRubricaHol = new javax.swing.JPanel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        btnCursosMed = new javax.swing.JPanel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        btnMedicionRe = new javax.swing.JPanel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        btnPlanMedicionRe = new javax.swing.JPanel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        background.setBackground(new java.awt.Color(214, 217, 223));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panHeader.setBackground(new java.awt.Color(175, 58, 3));
        panHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(251, 241, 199));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-clase-28.png"))); // NOI18N
        jLabel15.setText("Informática - UNT");
        panHeader.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 236, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-tipo-de-piel-masculina-del-usuario-del-círculo-7-30.png"))); // NOI18N
        panHeader.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 30, 30));

        lblUsuario.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(251, 241, 199));
        lblUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panHeader.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 160, 30));

        background.add(panHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        panLateral.setBackground(new java.awt.Color(40, 40, 40));
        panLateral.setPreferredSize(new java.awt.Dimension(238, 648));

        panBotones.setBackground(new java.awt.Color(40, 40, 40));
        panBotones.setLayout(new java.awt.GridLayout(0, 1, 0, 4));

        btnInicio.setBackground(new java.awt.Color(80, 73, 69));
        btnInicio.setForeground(new java.awt.Color(153, 153, 153));
        btnInicio.setToolTipText("");
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInicioMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInicioMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicioMouseEntered(evt);
            }
        });

        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-página-principal-32_1.png"))); // NOI18N

        jLabel96.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(251, 241, 199));
        jLabel96.setText("Dashboard");

        javax.swing.GroupLayout btnInicioLayout = new javax.swing.GroupLayout(btnInicio);
        btnInicio.setLayout(btnInicioLayout);
        btnInicioLayout.setHorizontalGroup(
            btnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel77)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel96)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        btnInicioLayout.setVerticalGroup(
            btnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel77, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel96, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panBotones.add(btnInicio);

        btnPlanCurricular.setBackground(new java.awt.Color(80, 73, 69));
        btnPlanCurricular.setForeground(new java.awt.Color(153, 153, 153));
        btnPlanCurricular.setToolTipText("");
        btnPlanCurricular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlanCurricular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPlanCurricularMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPlanCurricularMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPlanCurricularMouseEntered(evt);
            }
        });

        jLabel97.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-card-file-box-32.png"))); // NOI18N

        jLabel98.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel98.setForeground(new java.awt.Color(251, 241, 199));
        jLabel98.setText("Plan Curricular");

        javax.swing.GroupLayout btnPlanCurricularLayout = new javax.swing.GroupLayout(btnPlanCurricular);
        btnPlanCurricular.setLayout(btnPlanCurricularLayout);
        btnPlanCurricularLayout.setHorizontalGroup(
            btnPlanCurricularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPlanCurricularLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel97)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel98)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        btnPlanCurricularLayout.setVerticalGroup(
            btnPlanCurricularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel97, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel98, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panBotones.add(btnPlanCurricular);

        btnEvaluacion.setBackground(new java.awt.Color(80, 73, 69));
        btnEvaluacion.setForeground(new java.awt.Color(153, 153, 153));
        btnEvaluacion.setToolTipText("");
        btnEvaluacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEvaluacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEvaluacionMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEvaluacionMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEvaluacionMouseEntered(evt);
            }
        });

        jLabel99.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-memo-32.png"))); // NOI18N

        jLabel100.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel100.setForeground(new java.awt.Color(251, 241, 199));
        jLabel100.setText("Año de Evaluación");

        javax.swing.GroupLayout btnEvaluacionLayout = new javax.swing.GroupLayout(btnEvaluacion);
        btnEvaluacion.setLayout(btnEvaluacionLayout);
        btnEvaluacionLayout.setHorizontalGroup(
            btnEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEvaluacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel99)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel100)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        btnEvaluacionLayout.setVerticalGroup(
            btnEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel99, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel100, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panBotones.add(btnEvaluacion);

        btnResEstudiante.setBackground(new java.awt.Color(80, 73, 69));
        btnResEstudiante.setForeground(new java.awt.Color(153, 153, 153));
        btnResEstudiante.setToolTipText("");
        btnResEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnResEstudianteMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResEstudianteMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnResEstudianteMouseEntered(evt);
            }
        });

        jLabel101.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-page-facing-up-32.png"))); // NOI18N

        jLabel102.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(251, 241, 199));
        jLabel102.setText("Res. Estudiante");

        javax.swing.GroupLayout btnResEstudianteLayout = new javax.swing.GroupLayout(btnResEstudiante);
        btnResEstudiante.setLayout(btnResEstudianteLayout);
        btnResEstudianteLayout.setHorizontalGroup(
            btnResEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnResEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel101)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel102)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        btnResEstudianteLayout.setVerticalGroup(
            btnResEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel101, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel102, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panBotones.add(btnResEstudiante);

        btnCursos.setBackground(new java.awt.Color(80, 73, 69));
        btnCursos.setForeground(new java.awt.Color(153, 153, 153));
        btnCursos.setToolTipText("");
        btnCursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCursosMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCursosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCursosMouseEntered(evt);
            }
        });

        jLabel103.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-books-emoji-32.png"))); // NOI18N

        jLabel104.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(251, 241, 199));
        jLabel104.setText("Cursos");

        javax.swing.GroupLayout btnCursosLayout = new javax.swing.GroupLayout(btnCursos);
        btnCursos.setLayout(btnCursosLayout);
        btnCursosLayout.setHorizontalGroup(
            btnCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel103)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel104)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        btnCursosLayout.setVerticalGroup(
            btnCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel103, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel104, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panBotones.add(btnCursos);

        btnEstudiantes.setBackground(new java.awt.Color(80, 73, 69));
        btnEstudiantes.setForeground(new java.awt.Color(153, 153, 153));
        btnEstudiantes.setToolTipText("");
        btnEstudiantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEstudiantesMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEstudiantesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEstudiantesMouseEntered(evt);
            }
        });

        jLabel105.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-graduation-cap-32.png"))); // NOI18N

        jLabel106.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel106.setForeground(new java.awt.Color(251, 241, 199));
        jLabel106.setText("Estudiantes");

        javax.swing.GroupLayout btnEstudiantesLayout = new javax.swing.GroupLayout(btnEstudiantes);
        btnEstudiantes.setLayout(btnEstudiantesLayout);
        btnEstudiantesLayout.setHorizontalGroup(
            btnEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEstudiantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel105)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel106)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        btnEstudiantesLayout.setVerticalGroup(
            btnEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel105, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel106, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panBotones.add(btnEstudiantes);

        btnUsuarios.setBackground(new java.awt.Color(80, 73, 69));
        btnUsuarios.setForeground(new java.awt.Color(153, 153, 153));
        btnUsuarios.setToolTipText("");
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUsuariosMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseEntered(evt);
            }
        });

        jLabel107.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-busts-in-silhouette-32.png"))); // NOI18N

        jLabel108.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(251, 241, 199));
        jLabel108.setText("Usuarios");

        javax.swing.GroupLayout btnUsuariosLayout = new javax.swing.GroupLayout(btnUsuarios);
        btnUsuarios.setLayout(btnUsuariosLayout);
        btnUsuariosLayout.setHorizontalGroup(
            btnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel107)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel108)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        btnUsuariosLayout.setVerticalGroup(
            btnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel107, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel108, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panBotones.add(btnUsuarios);

        btnAsignar.setBackground(new java.awt.Color(80, 73, 69));
        btnAsignar.setForeground(new java.awt.Color(153, 153, 153));
        btnAsignar.setToolTipText("");
        btnAsignar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAsignar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAsignarMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAsignarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAsignarMouseEntered(evt);
            }
        });

        jLabel109.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-asignación-entregado-32.png"))); // NOI18N

        jLabel110.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel110.setForeground(new java.awt.Color(251, 241, 199));
        jLabel110.setText("Asignaciones");

        javax.swing.GroupLayout btnAsignarLayout = new javax.swing.GroupLayout(btnAsignar);
        btnAsignar.setLayout(btnAsignarLayout);
        btnAsignarLayout.setHorizontalGroup(
            btnAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAsignarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel109, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel110)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        btnAsignarLayout.setVerticalGroup(
            btnAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel109, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel110, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panBotones.add(btnAsignar);

        btnRubricaHol.setBackground(new java.awt.Color(80, 73, 69));
        btnRubricaHol.setForeground(new java.awt.Color(153, 153, 153));
        btnRubricaHol.setToolTipText("");
        btnRubricaHol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRubricaHol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRubricaHolMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRubricaHolMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRubricaHolMouseEntered(evt);
            }
        });

        jLabel111.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-clipboard-32.png"))); // NOI18N

        jLabel112.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(251, 241, 199));
        jLabel112.setText("Rúbrica Holística");

        javax.swing.GroupLayout btnRubricaHolLayout = new javax.swing.GroupLayout(btnRubricaHol);
        btnRubricaHol.setLayout(btnRubricaHolLayout);
        btnRubricaHolLayout.setHorizontalGroup(
            btnRubricaHolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRubricaHolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel111)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel112)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        btnRubricaHolLayout.setVerticalGroup(
            btnRubricaHolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel112, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panBotones.add(btnRubricaHol);

        btnCursosMed.setBackground(new java.awt.Color(80, 73, 69));
        btnCursosMed.setForeground(new java.awt.Color(153, 153, 153));
        btnCursosMed.setToolTipText("");
        btnCursosMed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCursosMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCursosMedMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCursosMedMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCursosMedMouseEntered(evt);
            }
        });

        jLabel113.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-open-book-emoji-28.png"))); // NOI18N

        jLabel114.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel114.setForeground(new java.awt.Color(251, 241, 199));
        jLabel114.setText("Cursos de Medición");

        javax.swing.GroupLayout btnCursosMedLayout = new javax.swing.GroupLayout(btnCursosMed);
        btnCursosMed.setLayout(btnCursosMedLayout);
        btnCursosMedLayout.setHorizontalGroup(
            btnCursosMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCursosMedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel113)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel114)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        btnCursosMedLayout.setVerticalGroup(
            btnCursosMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel113, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel114, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panBotones.add(btnCursosMed);

        btnMedicionRe.setBackground(new java.awt.Color(80, 73, 69));
        btnMedicionRe.setForeground(new java.awt.Color(153, 153, 153));
        btnMedicionRe.setToolTipText("");
        btnMedicionRe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMedicionRe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMedicionReMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMedicionReMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMedicionReMouseEntered(evt);
            }
        });

        jLabel115.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-bar-chart-32.png"))); // NOI18N

        jLabel116.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel116.setForeground(new java.awt.Color(251, 241, 199));
        jLabel116.setText("Medición RE");

        javax.swing.GroupLayout btnMedicionReLayout = new javax.swing.GroupLayout(btnMedicionRe);
        btnMedicionRe.setLayout(btnMedicionReLayout);
        btnMedicionReLayout.setHorizontalGroup(
            btnMedicionReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMedicionReLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel115)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel116)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        btnMedicionReLayout.setVerticalGroup(
            btnMedicionReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel115, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel116, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panBotones.add(btnMedicionRe);

        btnPlanMedicionRe.setBackground(new java.awt.Color(80, 73, 69));
        btnPlanMedicionRe.setForeground(new java.awt.Color(153, 153, 153));
        btnPlanMedicionRe.setToolTipText("");
        btnPlanMedicionRe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlanMedicionRe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPlanMedicionReMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPlanMedicionReMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPlanMedicionReMouseEntered(evt);
            }
        });

        jLabel117.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-chart-increasing-32.png"))); // NOI18N

        jLabel118.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel118.setForeground(new java.awt.Color(251, 241, 199));
        jLabel118.setText("Plan de Medición");

        javax.swing.GroupLayout btnPlanMedicionReLayout = new javax.swing.GroupLayout(btnPlanMedicionRe);
        btnPlanMedicionRe.setLayout(btnPlanMedicionReLayout);
        btnPlanMedicionReLayout.setHorizontalGroup(
            btnPlanMedicionReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPlanMedicionReLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel117)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel118)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        btnPlanMedicionReLayout.setVerticalGroup(
            btnPlanMedicionReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel117, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel118, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panBotones.add(btnPlanMedicionRe);

        javax.swing.GroupLayout panLateralLayout = new javax.swing.GroupLayout(panLateral);
        panLateral.setLayout(panLateralLayout);
        panLateralLayout.setHorizontalGroup(
            panLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panLateralLayout.setVerticalGroup(
            panLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        background.add(panLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 22, -1, 650));

        content.setBackground(new java.awt.Color(214, 217, 223));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        background.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 840, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     void setColor(JPanel panel){
        panel.setBackground(new Color(29,32,33));
        //orange [175,58,3]
        //fg [60,56,54]
        //fg0 [40,40,40]
        //aqua [66,123,88]
        //blue [7,102,120]
        //fg4 [124,111,100] fondo de boton
        
    }
            
     
    void resetColor(JPanel panel){
        panel.setBackground(new Color(80,73,69));
    }
    
    private void btnInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMousePressed
        setColor(btnInicio);
        resetColor(btnPlanCurricular);
        resetColor(btnEvaluacion);
        resetColor(btnResEstudiante);
        resetColor(btnCursos);
        resetColor(btnEstudiantes);
        resetColor(btnUsuarios);
        resetColor(btnAsignar);
        resetColor(btnRubricaHol);
        resetColor(btnCursosMed);
        resetColor(btnMedicionRe);
        resetColor(btnPlanMedicionRe);
        // Abrir sección
        PanDashboard panDashboard = new PanDashboard();
        panDashboard.setSize(842, 640);
        panDashboard.setLocation(0,0);

        content.removeAll();
        content.add(panDashboard, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnInicioMousePressed

    private void btnInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseExited
        if(btnPlanCurricular.getBackground().getRGB() != bg || btnEvaluacion.getBackground().getRGB() != bg || btnResEstudiante.getBackground().getRGB() != bg
            || btnCursos.getBackground().getRGB() != bg || btnEstudiantes.getBackground().getRGB() != bg || btnUsuarios.getBackground().getRGB() != bg
            || btnAsignar.getBackground().getRGB() != bg || btnRubricaHol.getBackground().getRGB() != bg || btnCursosMed.getBackground().getRGB() != bg
            || btnMedicionRe.getBackground().getRGB() != bg || btnPlanMedicionRe.getBackground().getRGB() != bg)
        resetColor(btnInicio);
    }//GEN-LAST:event_btnInicioMouseExited

    private void btnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseEntered
        if(btnInicio.getBackground().getRGB() == bg)
        setColor(btnInicio);
    }//GEN-LAST:event_btnInicioMouseEntered

    private void btnPlanCurricularMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlanCurricularMousePressed
        setColor(btnPlanCurricular);
        resetColor(btnInicio);
        resetColor(btnEvaluacion);
        resetColor(btnResEstudiante);
        resetColor(btnCursos);
        resetColor(btnEstudiantes);
        resetColor(btnUsuarios);
        resetColor(btnAsignar);
        resetColor(btnRubricaHol);
        resetColor(btnCursosMed);
        resetColor(btnMedicionRe);
        resetColor(btnPlanMedicionRe);
        // Abrir sección
        PanPlanCurricular panPlanCurricular = new PanPlanCurricular();
        panPlanCurricular.setSize(840, 640);
        panPlanCurricular.setLocation(0,0);

        content.removeAll();
        content.add(panPlanCurricular, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnPlanCurricularMousePressed

    private void btnPlanCurricularMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlanCurricularMouseExited
        if(btnInicio.getBackground().getRGB() != bg || btnEvaluacion.getBackground().getRGB() != bg || btnResEstudiante.getBackground().getRGB() != bg
            || btnCursos.getBackground().getRGB() != bg || btnEstudiantes.getBackground().getRGB() != bg || btnUsuarios.getBackground().getRGB() != bg
            || btnAsignar.getBackground().getRGB() != bg || btnRubricaHol.getBackground().getRGB() != bg || btnCursosMed.getBackground().getRGB() != bg
            || btnMedicionRe.getBackground().getRGB() != bg || btnPlanMedicionRe.getBackground().getRGB() != bg)
        resetColor(btnPlanCurricular);
    }//GEN-LAST:event_btnPlanCurricularMouseExited

    private void btnPlanCurricularMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlanCurricularMouseEntered
        if(btnPlanCurricular.getBackground().getRGB() == bg)
        setColor(btnPlanCurricular);
    }//GEN-LAST:event_btnPlanCurricularMouseEntered

    private void btnEvaluacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEvaluacionMousePressed
        setColor(btnEvaluacion);
        resetColor(btnInicio);
        resetColor(btnPlanCurricular);
        resetColor(btnResEstudiante);
        resetColor(btnCursos);
        resetColor(btnEstudiantes);
        resetColor(btnUsuarios);
        resetColor(btnAsignar);
        resetColor(btnRubricaHol);
        resetColor(btnCursosMed);
        resetColor(btnMedicionRe);
        resetColor(btnPlanMedicionRe);
        // Abrir sección
        PanAnioEvaluacion panAnioEvaluacion = new PanAnioEvaluacion();
        panAnioEvaluacion.setSize(842, 640);
        panAnioEvaluacion.setLocation(0,0);

        content.removeAll();
        content.add(panAnioEvaluacion, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnEvaluacionMousePressed

    private void btnEvaluacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEvaluacionMouseExited
        if(btnPlanCurricular.getBackground().getRGB() != bg || btnInicio.getBackground().getRGB() != bg || btnResEstudiante.getBackground().getRGB() != bg
            || btnCursos.getBackground().getRGB() != bg || btnEstudiantes.getBackground().getRGB() != bg || btnUsuarios.getBackground().getRGB() != bg
            || btnAsignar.getBackground().getRGB() != bg || btnRubricaHol.getBackground().getRGB() != bg || btnCursosMed.getBackground().getRGB() != bg
            || btnMedicionRe.getBackground().getRGB() != bg || btnPlanMedicionRe.getBackground().getRGB() != bg)
        resetColor(btnEvaluacion);
    }//GEN-LAST:event_btnEvaluacionMouseExited

    private void btnEvaluacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEvaluacionMouseEntered
        if(btnEvaluacion.getBackground().getRGB() == bg)
        setColor(btnEvaluacion);
    }//GEN-LAST:event_btnEvaluacionMouseEntered

    private void btnResEstudianteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResEstudianteMousePressed
        setColor(btnResEstudiante);
        resetColor(btnPlanCurricular);
        resetColor(btnEvaluacion);
        resetColor(btnInicio);
        resetColor(btnCursos);
        resetColor(btnEstudiantes);
        resetColor(btnUsuarios);
        resetColor(btnAsignar);
        resetColor(btnRubricaHol);
        resetColor(btnCursosMed);
        resetColor(btnMedicionRe);
        resetColor(btnPlanMedicionRe);
        // Abrir sección
        PanResEstudiantes panResEstudiante = new PanResEstudiantes();
        panResEstudiante.setSize(842, 640);
        panResEstudiante.setLocation(0,0);

        content.removeAll();
        content.add(panResEstudiante, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnResEstudianteMousePressed

    private void btnResEstudianteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResEstudianteMouseExited
        if(btnPlanCurricular.getBackground().getRGB() != bg || btnEvaluacion.getBackground().getRGB() != bg || btnInicio.getBackground().getRGB() != bg
            || btnCursos.getBackground().getRGB() != bg || btnEstudiantes.getBackground().getRGB() != bg || btnUsuarios.getBackground().getRGB() != bg
            || btnAsignar.getBackground().getRGB() != bg || btnRubricaHol.getBackground().getRGB() != bg || btnCursosMed.getBackground().getRGB() != bg
            || btnMedicionRe.getBackground().getRGB() != bg || btnPlanMedicionRe.getBackground().getRGB() != bg)
        resetColor(btnResEstudiante);
    }//GEN-LAST:event_btnResEstudianteMouseExited

    private void btnResEstudianteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResEstudianteMouseEntered
        if(btnResEstudiante.getBackground().getRGB() == bg)
        setColor(btnResEstudiante);
    }//GEN-LAST:event_btnResEstudianteMouseEntered

    private void btnCursosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCursosMousePressed
        setColor(btnCursos);
        resetColor(btnPlanCurricular);
        resetColor(btnEvaluacion);
        resetColor(btnResEstudiante);
        resetColor(btnInicio);
        resetColor(btnEstudiantes);
        resetColor(btnUsuarios);
        resetColor(btnAsignar);
        resetColor(btnRubricaHol);
        resetColor(btnCursosMed);
        resetColor(btnMedicionRe);
        resetColor(btnPlanMedicionRe);
        // Abrir sección
        PanCursos panCursos = new PanCursos();
        panCursos.setSize(842, 640);
        panCursos.setLocation(0,0);

        content.removeAll();
        content.add(panCursos, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnCursosMousePressed

    private void btnCursosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCursosMouseExited
        if(btnPlanCurricular.getBackground().getRGB() != bg || btnEvaluacion.getBackground().getRGB() != bg || btnResEstudiante.getBackground().getRGB() != bg
            || btnInicio.getBackground().getRGB() != bg || btnEstudiantes.getBackground().getRGB() != bg || btnUsuarios.getBackground().getRGB() != bg
            || btnAsignar.getBackground().getRGB() != bg || btnRubricaHol.getBackground().getRGB() != bg || btnCursosMed.getBackground().getRGB() != bg
            || btnMedicionRe.getBackground().getRGB() != bg || btnPlanMedicionRe.getBackground().getRGB() != bg)
        resetColor(btnCursos);
    }//GEN-LAST:event_btnCursosMouseExited

    private void btnCursosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCursosMouseEntered
        if(btnCursos.getBackground().getRGB() == bg)
        setColor(btnCursos);
    }//GEN-LAST:event_btnCursosMouseEntered

    private void btnEstudiantesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstudiantesMousePressed
        setColor(btnEstudiantes);
        resetColor(btnPlanCurricular);
        resetColor(btnEvaluacion);
        resetColor(btnResEstudiante);
        resetColor(btnCursos);
        resetColor(btnInicio);
        resetColor(btnUsuarios);
        resetColor(btnAsignar);
        resetColor(btnRubricaHol);
        resetColor(btnCursosMed);
        resetColor(btnMedicionRe);
        resetColor(btnPlanMedicionRe);
        // Abrir sección
        PanEstudiantes panEstudiantes = new PanEstudiantes();
        panEstudiantes.setSize(842, 640);
        panEstudiantes.setLocation(0,0);

        content.removeAll();
        content.add(panEstudiantes, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnEstudiantesMousePressed

    private void btnEstudiantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstudiantesMouseExited
        if(btnPlanCurricular.getBackground().getRGB() != bg || btnEvaluacion.getBackground().getRGB() != bg || btnResEstudiante.getBackground().getRGB() != bg
            || btnCursos.getBackground().getRGB() != bg || btnInicio.getBackground().getRGB() != bg || btnUsuarios.getBackground().getRGB() != bg
            || btnAsignar.getBackground().getRGB() != bg || btnRubricaHol.getBackground().getRGB() != bg || btnCursosMed.getBackground().getRGB() != bg
            || btnMedicionRe.getBackground().getRGB() != bg || btnPlanMedicionRe.getBackground().getRGB() != bg)
        resetColor(btnEstudiantes);
    }//GEN-LAST:event_btnEstudiantesMouseExited

    private void btnEstudiantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstudiantesMouseEntered
        if(btnEstudiantes.getBackground().getRGB() == bg)
        setColor(btnEstudiantes);
    }//GEN-LAST:event_btnEstudiantesMouseEntered

    private void btnUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMousePressed
        setColor(btnUsuarios);
        resetColor(btnPlanCurricular);
        resetColor(btnEvaluacion);
        resetColor(btnResEstudiante);
        resetColor(btnCursos);
        resetColor(btnEstudiantes);
        resetColor(btnInicio);
        resetColor(btnAsignar);
        resetColor(btnRubricaHol);
        resetColor(btnCursosMed);
        resetColor(btnMedicionRe);
        resetColor(btnPlanMedicionRe);
        // Abrir sección
        
        PanUsuarios panUsuarios = new PanUsuarios();
        panUsuarios.setSize(842, 640);
        panUsuarios.setLocation(0,0);
        
        content.removeAll();
        content.add(panUsuarios, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnUsuariosMousePressed

    private void btnUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseExited
        if(btnPlanCurricular.getBackground().getRGB() != bg || btnEvaluacion.getBackground().getRGB() != bg || btnResEstudiante.getBackground().getRGB() != bg
            || btnCursos.getBackground().getRGB() != bg || btnEstudiantes.getBackground().getRGB() != bg || btnInicio.getBackground().getRGB() != bg
            || btnAsignar.getBackground().getRGB() != bg || btnRubricaHol.getBackground().getRGB() != bg || btnCursosMed.getBackground().getRGB() != bg
            || btnMedicionRe.getBackground().getRGB() != bg || btnPlanMedicionRe.getBackground().getRGB() != bg)
        resetColor(btnUsuarios);
    }//GEN-LAST:event_btnUsuariosMouseExited

    private void btnUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseEntered
        if(btnUsuarios.getBackground().getRGB() == bg)
        setColor(btnUsuarios);
    }//GEN-LAST:event_btnUsuariosMouseEntered

    private void btnAsignarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsignarMousePressed
        setColor(btnAsignar);
        resetColor(btnPlanCurricular);
        resetColor(btnEvaluacion);
        resetColor(btnResEstudiante);
        resetColor(btnCursos);
        resetColor(btnEstudiantes);
        resetColor(btnUsuarios);
        resetColor(btnInicio);
        resetColor(btnRubricaHol);
        resetColor(btnCursosMed);
        resetColor(btnMedicionRe);
        resetColor(btnPlanMedicionRe);
        // Abrir sección
        PanAsignar panAsignar = new PanAsignar();
        panAsignar.setSize(842, 640);
        panAsignar.setLocation(0,0);

        content.removeAll();
        content.add(panAsignar, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnAsignarMousePressed

    private void btnAsignarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsignarMouseExited
        if(btnPlanCurricular.getBackground().getRGB() != bg || btnEvaluacion.getBackground().getRGB() != bg || btnResEstudiante.getBackground().getRGB() != bg
            || btnCursos.getBackground().getRGB() != bg || btnEstudiantes.getBackground().getRGB() != bg || btnUsuarios.getBackground().getRGB() != bg
            || btnInicio.getBackground().getRGB() != bg || btnRubricaHol.getBackground().getRGB() != bg || btnCursosMed.getBackground().getRGB() != bg
            || btnMedicionRe.getBackground().getRGB() != bg || btnPlanMedicionRe.getBackground().getRGB() != bg)
        resetColor(btnAsignar);
    }//GEN-LAST:event_btnAsignarMouseExited

    private void btnAsignarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsignarMouseEntered
        if(btnAsignar.getBackground().getRGB() == bg)
        setColor(btnAsignar);
    }//GEN-LAST:event_btnAsignarMouseEntered

    private void btnRubricaHolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRubricaHolMousePressed
        setColor(btnRubricaHol);
        resetColor(btnPlanCurricular);
        resetColor(btnEvaluacion);
        resetColor(btnResEstudiante);
        resetColor(btnCursos);
        resetColor(btnEstudiantes);
        resetColor(btnUsuarios);
        resetColor(btnAsignar);
        resetColor(btnInicio);
        resetColor(btnCursosMed);
        resetColor(btnMedicionRe);
        resetColor(btnPlanMedicionRe);
        // Abrir sección
        PanRubricaHol panRubricaHol = new PanRubricaHol();
        panRubricaHol.setSize(842, 640);
        panRubricaHol.setLocation(0,0);

        content.removeAll();
        content.add(panRubricaHol, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnRubricaHolMousePressed

    private void btnRubricaHolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRubricaHolMouseExited
        if(btnPlanCurricular.getBackground().getRGB() != bg || btnEvaluacion.getBackground().getRGB() != bg || btnResEstudiante.getBackground().getRGB() != bg
            || btnCursos.getBackground().getRGB() != bg || btnEstudiantes.getBackground().getRGB() != bg || btnUsuarios.getBackground().getRGB() != bg
            || btnAsignar.getBackground().getRGB() != bg || btnInicio.getBackground().getRGB() != bg || btnCursosMed.getBackground().getRGB() != bg
            || btnMedicionRe.getBackground().getRGB() != bg || btnPlanMedicionRe.getBackground().getRGB() != bg)
        resetColor(btnRubricaHol);
    }//GEN-LAST:event_btnRubricaHolMouseExited

    private void btnRubricaHolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRubricaHolMouseEntered
        if(btnRubricaHol.getBackground().getRGB() == bg)
        setColor(btnRubricaHol);
    }//GEN-LAST:event_btnRubricaHolMouseEntered

    private void btnCursosMedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCursosMedMousePressed
        setColor(btnCursosMed);
        resetColor(btnPlanCurricular);
        resetColor(btnEvaluacion);
        resetColor(btnResEstudiante);
        resetColor(btnCursos);
        resetColor(btnEstudiantes);
        resetColor(btnUsuarios);
        resetColor(btnAsignar);
        resetColor(btnRubricaHol);
        resetColor(btnInicio);
        resetColor(btnMedicionRe);
        resetColor(btnPlanMedicionRe);
        // Abrir sección
        PanCursosMed panCursos = new PanCursosMed();
        panCursos.setSize(842, 640);
        panCursos.setLocation(0,0);

        content.removeAll();
        content.add(panCursos, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnCursosMedMousePressed

    private void btnCursosMedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCursosMedMouseExited
        if(btnPlanCurricular.getBackground().getRGB() != bg || btnEvaluacion.getBackground().getRGB() != bg || btnResEstudiante.getBackground().getRGB() != bg
            || btnCursos.getBackground().getRGB() != bg || btnEstudiantes.getBackground().getRGB() != bg || btnUsuarios.getBackground().getRGB() != bg
            || btnAsignar.getBackground().getRGB() != bg || btnRubricaHol.getBackground().getRGB() != bg || btnInicio.getBackground().getRGB() != bg
            || btnMedicionRe.getBackground().getRGB() != bg || btnPlanMedicionRe.getBackground().getRGB() != bg)
        resetColor(btnCursosMed);
    }//GEN-LAST:event_btnCursosMedMouseExited

    private void btnCursosMedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCursosMedMouseEntered
        if(btnCursosMed.getBackground().getRGB() == bg)
        setColor(btnCursosMed);
    }//GEN-LAST:event_btnCursosMedMouseEntered

    private void btnMedicionReMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedicionReMousePressed
        setColor(btnMedicionRe);
        resetColor(btnPlanCurricular);
        resetColor(btnEvaluacion);
        resetColor(btnResEstudiante);
        resetColor(btnCursos);
        resetColor(btnEstudiantes);
        resetColor(btnUsuarios);
        resetColor(btnAsignar);
        resetColor(btnRubricaHol);
        resetColor(btnCursosMed);
        resetColor(btnInicio);
        resetColor(btnPlanMedicionRe);
        // Abrir sección
        PanMedicionRe panMedicionRe = new PanMedicionRe();
        panMedicionRe.setSize(842, 640);
        panMedicionRe.setLocation(0,0);

        content.removeAll();
        content.add(panMedicionRe, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnMedicionReMousePressed

    private void btnMedicionReMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedicionReMouseExited
        if(btnPlanCurricular.getBackground().getRGB() != bg || btnEvaluacion.getBackground().getRGB() != bg || btnResEstudiante.getBackground().getRGB() != bg
            || btnCursos.getBackground().getRGB() != bg || btnEstudiantes.getBackground().getRGB() != bg || btnUsuarios.getBackground().getRGB() != bg
            || btnAsignar.getBackground().getRGB() != bg || btnRubricaHol.getBackground().getRGB() != bg || btnCursosMed.getBackground().getRGB() != bg
            || btnInicio.getBackground().getRGB() != bg || btnPlanMedicionRe.getBackground().getRGB() != bg)
        resetColor(btnMedicionRe);
    }//GEN-LAST:event_btnMedicionReMouseExited

    private void btnMedicionReMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedicionReMouseEntered
        if(btnMedicionRe.getBackground().getRGB() == bg)
        setColor(btnMedicionRe);
    }//GEN-LAST:event_btnMedicionReMouseEntered

    private void btnPlanMedicionReMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlanMedicionReMousePressed
        setColor(btnPlanMedicionRe);
        resetColor(btnPlanCurricular);
        resetColor(btnEvaluacion);
        resetColor(btnResEstudiante);
        resetColor(btnCursos);
        resetColor(btnEstudiantes);
        resetColor(btnUsuarios);
        resetColor(btnAsignar);
        resetColor(btnRubricaHol);
        resetColor(btnCursosMed);
        resetColor(btnMedicionRe);
        resetColor(btnInicio);
        // Abrir sección
        PanPlanMedicionRe panPlanMedicionRe = new PanPlanMedicionRe();
        panPlanMedicionRe.setSize(842, 640);
        panPlanMedicionRe.setLocation(0,0);

        content.removeAll();
        content.add(panPlanMedicionRe, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnPlanMedicionReMousePressed

    private void btnPlanMedicionReMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlanMedicionReMouseExited
        if(btnPlanCurricular.getBackground().getRGB() != bg || btnEvaluacion.getBackground().getRGB() != bg || btnResEstudiante.getBackground().getRGB() != bg
            || btnCursos.getBackground().getRGB() != bg || btnEstudiantes.getBackground().getRGB() != bg || btnUsuarios.getBackground().getRGB() != bg
            || btnAsignar.getBackground().getRGB() != bg || btnRubricaHol.getBackground().getRGB() != bg || btnCursosMed.getBackground().getRGB() != bg
            || btnMedicionRe.getBackground().getRGB() != bg || btnInicio.getBackground().getRGB() != bg)
        resetColor(btnPlanMedicionRe);
    }//GEN-LAST:event_btnPlanMedicionReMouseExited

    private void btnPlanMedicionReMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlanMedicionReMouseEntered
        if(btnPlanMedicionRe.getBackground().getRGB() == bg)
        setColor(btnPlanMedicionRe);
    }//GEN-LAST:event_btnPlanMedicionReMouseEntered

    private void identificarUsuario() {
        //if (admin.getApellido() != null)
        if (admin.isPrivilegios()) //true
            lblUsuario.setText("Superuser: " + admin.getNombre()+" "+admin.getApellido());
        else
            lblUsuario.setText("Admin: " + admin.getNombre()+" "+admin.getApellido());
    }
    
    //eventos para cargar datos
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       identificarUsuario();
       
       //carga el dasboard de admin
        PanDashboard panDashboard = new PanDashboard();
        panDashboard.setSize(842, 640);
        panDashboard.setLocation(0,0);

        content.removeAll();
        content.add(panDashboard, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_formWindowOpened

    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DashboardAdmin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel btnAsignar;
    private javax.swing.JPanel btnCursos;
    private javax.swing.JPanel btnCursosMed;
    private javax.swing.JPanel btnEstudiantes;
    private javax.swing.JPanel btnEvaluacion;
    private javax.swing.JPanel btnInicio;
    private javax.swing.JPanel btnMedicionRe;
    private javax.swing.JPanel btnPlanCurricular;
    private javax.swing.JPanel btnPlanMedicionRe;
    private javax.swing.JPanel btnResEstudiante;
    private javax.swing.JPanel btnRubricaHol;
    private javax.swing.JPanel btnUsuarios;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panBotones;
    private javax.swing.JPanel panHeader;
    private javax.swing.JPanel panLateral;
    // End of variables declaration//GEN-END:variables
}
