
package view;

/**
 *
 * @author alfie
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblPasswd = new javax.swing.JLabel();
        pwdPassword = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        lblTipo = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        lblIniciarSesin = new javax.swing.JLabel();
        lblLogoIcacit = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();
        panBarra = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 102));
        lblUsuario.setText("USUARIO");
        panPrincipal.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setText(" Ingrese su nombre de usuario");
        txtUsuario.setBorder(null);
        panPrincipal.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 320, 30));

        jSeparator2.setBackground(new java.awt.Color(166, 55, 55));
        jSeparator2.setForeground(new java.awt.Color(166, 55, 55));
        panPrincipal.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 320, 10));

        lblPasswd.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblPasswd.setForeground(new java.awt.Color(0, 0, 102));
        lblPasswd.setText("CONTRASEÑA");
        panPrincipal.add(lblPasswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        pwdPassword.setBackground(new java.awt.Color(255, 255, 255));
        pwdPassword.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        pwdPassword.setForeground(new java.awt.Color(204, 204, 204));
        pwdPassword.setText("  jPasswordField1");
        pwdPassword.setBorder(null);
        panPrincipal.add(pwdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 320, 30));

        jSeparator3.setBackground(new java.awt.Color(166, 55, 55));
        jSeparator3.setForeground(new java.awt.Color(166, 55, 55));
        panPrincipal.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 320, 10));

        lblTipo.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(0, 0, 102));
        lblTipo.setText("TIPO");
        panPrincipal.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Profesor", "Administrador" }));
        jComboBox1.setBorder(null);
        panPrincipal.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 320, 30));

        jSeparator1.setBackground(new java.awt.Color(166, 55, 55));
        jSeparator1.setForeground(new java.awt.Color(166, 55, 55));
        panPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 320, 10));

        lblIniciarSesin.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblIniciarSesin.setForeground(new java.awt.Color(0, 0, 102));
        lblIniciarSesin.setText("INICIAR SESIÓN");
        panPrincipal.add(lblIniciarSesin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        lblLogoIcacit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLogoIcacit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo_ICACIT.png"))); // NOI18N
        lblLogoIcacit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panPrincipal.add(lblLogoIcacit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 380, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-menú-32.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panPrincipal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, 30, 20));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnIngresar.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnIngresarBg.png"))); // NOI18N
        jButton2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnIngresarBg.png"))); // NOI18N
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnIngresar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panPrincipal.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 170, 50));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.png"))); // NOI18N
        panPrincipal.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        javax.swing.GroupLayout panBarraLayout = new javax.swing.GroupLayout(panBarra);
        panBarra.setLayout(panBarraLayout);
        panBarraLayout.setHorizontalGroup(
            panBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        panBarraLayout.setVerticalGroup(
            panBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panPrincipal.add(panBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIniciarSesin;
    private javax.swing.JLabel lblLogoIcacit;
    private javax.swing.JLabel lblPasswd;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panBarra;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
