/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import beans.PlanCurricular;
import Utilidades.Utilitarios;
import java.awt.Font;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.Date;
import log.PlanCurricularLog;

/**
 *
 * @author alfie
 */
public class PanPlanCurricular extends javax.swing.JPanel {
    boolean privilegio = DashboardAdmin.admin.isPrivilegios(); //acceso a datos
    byte sedeId = DashboardAdmin.admin.getSedeId(); //sede a la que pertenece
    PlanCurricularLog obj = new PlanCurricularLog();
    PlanCurricular auxPlanCurricular;
    boolean band = false;
    /**
     * Creates new form PanPlanCurricular
     */
    public PanPlanCurricular() {
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCodPlan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPlanEstudios = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFechaPlan = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPlan = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setBackground(new java.awt.Color(214, 217, 223));
        setPreferredSize(new java.awt.Dimension(840, 640));

        jPanel6.setBackground(new java.awt.Color(214, 217, 223));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("JetBrainsMono Nerd Font", 2, 12), new java.awt.Color(175, 58, 3))); // NOI18N

        jLabel3.setFont(new java.awt.Font("JetBrainsMono Nerd Font", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(29, 32, 33));
        jLabel3.setText("Código:");

        txtCodPlan.setFont(new java.awt.Font("JetBrainsMono Nerd Font", 0, 14)); // NOI18N
        txtCodPlan.setForeground(new java.awt.Color(29, 32, 33));
        txtCodPlan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodPlanKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("JetBrainsMono Nerd Font", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(29, 32, 33));
        jLabel5.setText("Plan Estudios:");

        txtPlanEstudios.setFont(new java.awt.Font("JetBrainsMono Nerd Font", 0, 14)); // NOI18N
        txtPlanEstudios.setForeground(new java.awt.Color(29, 32, 33));
        txtPlanEstudios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlanEstudiosKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("JetBrainsMono Nerd Font", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(29, 32, 33));
        jLabel6.setText("Fecha Creación:");

        txtFechaPlan.setFont(new java.awt.Font("JetBrainsMono Nerd Font", 0, 14)); // NOI18N
        txtFechaPlan.setForeground(new java.awt.Color(29, 32, 33));
        txtFechaPlan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaPlanKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtCodPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtPlanEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txtFechaPlan, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtPlanEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtFechaPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(214, 217, 223));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visualización", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("JetBrainsMono Nerd Font", 2, 12), new java.awt.Color(175, 58, 3))); // NOI18N

        tblPlan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblPlan);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(214, 217, 223));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("JetBrainsMono Nerd Font", 2, 12), new java.awt.Color(175, 58, 3))); // NOI18N

        btnNuevo.setFont(new java.awt.Font("JetBrainsMono Nerd Font", 0, 14)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(29, 32, 33));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("JetBrainsMono Nerd Font", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(29, 32, 33));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("JetBrainsMono Nerd Font", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(29, 32, 33));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("JetBrainsMono Nerd Font", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(29, 32, 33));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("JetBrainsMono Nerd Font", 0, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(29, 32, 33));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 352, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cargarDatos() {
        tblPlan.setModel(obj.listTable());
        configTblUsuarios();
        mCajas(false, false);
        if (privilegio) //superusario
            mBotones(true, false, false, true);
        else
            mBotones(false, false, false, false);
    }
    
    private void configTblUsuarios() {
        //cargamos la tabla de usuarios
        tblPlan.getTableHeader().setReorderingAllowed(false); //captura el encabezado
        tblPlan.getTableHeader().setFont(new Font("JetBrainsMonoMedium Nerd Font", Font.PLAIN, 12));
        tblPlan.setRowHeight(20); //configura el tamaño de las celdas
        //Se define el tamaño de largo para cada columna y su contenido
        tblPlan.getColumnModel().getColumn(0).setPreferredWidth(50); //codigo
        tblPlan.getColumnModel().getColumn(1).setPreferredWidth(130); //plan
        tblPlan.getColumnModel().getColumn(2).setPreferredWidth(100); //fecha
    }
    
    private void txtCodPlanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodPlanKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
        if (txtCodPlan.getText().length() >= 2) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtCodPlanKeyTyped

    private void txtPlanEstudiosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlanEstudiosKeyTyped
       char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
        if (txtPlanEstudios.getText().length() >= 4) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtPlanEstudiosKeyTyped

    private void txtFechaPlanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaPlanKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')&& (c!='-') && (c!=':') && (c!=' '))
            evt.consume();
        if (txtFechaPlan.getText().length() >= 21) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtFechaPlanKeyTyped

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        band = true; //activa para guardar un nuevo elemento
        mLimpiar();
        mCajas(false, true);
        mBotones(false, true, false, false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String codigo = txtCodPlan.getText();
        String planEstudios = txtPlanEstudios.getText();
        Date fechaActual = Calendar.getInstance().getTime();
        if (!planEstudios.equals("")) {
            if (band) {//band = true guarda un plan curricular
                obj.agregar(planEstudios, fechaActual);
            } else { //band = false actualiza un plan curricular
                mEditable(true);
                if (!planEstudios.equals(auxPlanCurricular.getPlanEstudios())) {
                    int rpta = Utilitarios.confirmacion("El plan de estudios es un dato sensible, desea modificarlo?", 0);
                    if (rpta == 0)
                        obj.actualizar(auxPlanCurricular.getPlancId(), planEstudios);
                }
            }
            tblPlan.setModel(obj.listTable());
            configTblUsuarios();
            mCajas(false, false);
            mBotones(true, false, false, true);
            mLimpiar();
        } else {
            Utilitarios.mensaje("Ingrese todos los datos del formulario!!!", 2);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (txtCodPlan.getText().length() != 0) { //no esta vacio
            auxPlanCurricular = new PlanCurricular(Byte.parseByte(txtCodPlan.getText()));
            if (obj.buscar(auxPlanCurricular)) { //true fue encontrado
                txtPlanEstudios.setText(auxPlanCurricular.getPlanEstudios());
                txtFechaPlan.setText(String.valueOf(auxPlanCurricular.getFechaCreacion()));
                mEditable(false);
                mCajas(true, true);
                mBotones(false, true, false, false);
            } else {
                mLimpiar();
                mCajas(false, false);
                mBotones(true, false, false, true);
            }
        } else {
            txtCodPlan.setText("");
            Utilitarios.mensaje("Ingrese el dni a buscar", 2);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        band = false;
        txtCodPlan.setEnabled(true);
        mBotones(false, false, true, false);
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPlan;
    private javax.swing.JTextField txtCodPlan;
    private javax.swing.JTextField txtFechaPlan;
    private javax.swing.JTextField txtPlanEstudios;
    // End of variables declaration//GEN-END:variables

    private void mCajas(boolean a, boolean b) {
        txtCodPlan.setEnabled(a);
        txtPlanEstudios.setEnabled(b);
        txtFechaPlan.setEnabled(a);
    }

    private void mBotones(boolean a, boolean b, boolean c, boolean e) {
        btnNuevo.setEnabled(a);
        btnGuardar.setEnabled(b);
        btnBuscar.setEnabled(c);
        btnEliminar.setEnabled(false);
        btnEditar.setEnabled(e);
    }

    private void mLimpiar() {
        txtCodPlan.setText("");
        txtPlanEstudios.setText("");
        txtFechaPlan.setText("");
    }
    private void mEditable(boolean b) {
        txtCodPlan.setEditable(b);
        txtFechaPlan.setEditable(b);
    }
}
